version: '3'
services:
  web:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    networks:
      - niramaya_network

networks:
  niramaya_network:
    driver: bridge
